name: Release
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install

      - name: Bump and Tag
        run: |
          git config user.email "github-actions@users.noreply.github.com"
          git config user.name "GitHub Actions"
          pnpx changelogen@latest --release
          git push
          git push --tags

      - name: NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
          pnpm publish

      - name: GitHub Release
        run: pnpx changelogen@latest gh release --token ${{ secrets.GITHUB_TOKEN }}
